---
title: "for group 5"
author: "Ryan Attwood"
date: "`r Sys.Date()`"
output: html_document
---



```{r}
library(readxl)
data<-read_excel("C:/Users/ryana/Downloads/diabetes and predictors 4-18.xlsx")
# removing one county without diabetes info 
which(is.na(data$`Percent Diabetes 2013`))
data<-data[-2917, ]

#need to normalize CSA count 
data$`Community supported agriculture 2013 (count)`<- data$`Community supported agriculture 2013 (count)`/data$Population_Estimate_2013


#Binary to factor 
data$`FOOD_BANKS 2018`<-as.factor(data$`FOOD_BANKS 2018`)
data$`Persistant poverty counties 2010`<-as.factor(data$`Persistant poverty counties 2010`)
data$`metro / non metro county 2010`<-as.factor(data$`Persistant poverty counties 2010`)
data$`population loss county 2010`<-as.factor(data$`population loss county 2010`)

#State to region 


northeast<-c("ME","NH","MA","CT","RI","NY","PA","NJ")
south<-c("DC","MD","DE","WV","KY","TN","VA","NC","SC","GA","FL","AL","MS","LA","AR","OK","TX")
midwest<-c("OH","IN","MI","IL","WI","MO","IA","MN","ND","SD","NE","KS")


for (i in 1:nrow(data)){
if (data$State[i] %in% northeast){
  data$region[i] = "Northeast"
}
  else if (data$State[i] %in% south){
  data$region[i] = "South"}
  else if (data$State[i] %in% midwest){
    data$region[i] = "Midwest"
  }
  else if (data$region[i] == 0){
    data$region[i] = "West"
  }
}





#create binary outcome 
median_Diabetes<-median(data$`Percent Diabetes 2013`)
data$highlowDM<-ifelse(data$`Percent Diabetes 2013`> median_Diabetes,1,0)


```

```{r}
library(tidyverse)
library(ggplot2)
library(GGally)
EA_access<-data%>%
  select(`Percent Diabetes 2013`,`percent household low access 2015`,`Grocery per thousand 2011`,`Supercenter per thousand 2011`,`onvenience store per thousand 2011`,`Specialty store per thousand 2011`)
ggpairs(EA_access)

EA_restauraunt_security<-data%>%
  select(`Percent Diabetes 2013`,`Fast Food per thousand 2011`,`Full service restauraunt per thousand 2011`,`Statewide SNAP participation rate 2011`,`FOOD_BANKS 2018`,`Satewide food insecurity 12-14`)
ggpairs(EA_restauraunt_security)

EA_Farms<-data%>%
  select(`Percent Diabetes 2013`,`Direct farm sales per capita 2012`,`Farmers markets per capita 2013`,`Percent farmers market accepting SNAP 2013`,`Community supported agriculture 2013 (count)`)
ggpairs(EA_Farms)

EA_Demo<-data%>%
  select(`Percent Diabetes 2013`,region,`Statewide percent obesity  2012`,`Recreation and fitness facilties per 1000 2011`,)
ggpairs(EA_Demo)

EA_Race<-data%>%
  select(`Percent Diabetes 2013`,`percent white 2010`,`percent black  2010`,`percent hispanic 2010`,`percent asian 2010`,`percent native american 2010`,`percent pacific islander 2010`)
ggpairs(EA_Race)

EA_Money<-data%>%
  select(`Percent Diabetes 2013`, `Median household income 2015`,`Poverty rate 2015`,`Persistant poverty counties 2010`,`population loss county 2010`,`metro / non metro county 2010`,`percent 65 and older 2010`,`percent 18 or younger 2010`)
ggpairs(EA_Money)
```

    Marginal simple linear regressions.
    Multiple linear regression.
        Add polynomial terms or transformations of some of the predictors.
        Add at least two interaction terms that make sense to you.


